package in.co.rays.proj4.bean;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;

/**
 * Base bean class that provides common attributes and functionality
 * for all bean classes.
 *
 * @author Aayushi
 * @version 1.0
 */
public abstract class BaseBean implements DropdownListBean {

	/**
	 * Primary key of the record.
	 * It is a non-business key and is automatically generated by the database.
	 */
	protected long id;

	/**
	 * Name of the user who created the record.
	 */
	protected String createdBy;

	/**
	 * Name of the user who modified the record.
	 */
	protected String modifiedBy;

	/**
	 * Date and time when the record was created.
	 */
	protected Timestamp createdDatetime;

	/**
	 * Date and time when the record was modified.
	 */
	protected Timestamp modifiededDatetime;

	/**
	 * Returns the ID of the record.
	 *
	 * @return record ID
	 */
	public long getId() {
		return id;
	}

	/**
	 * Sets the ID of the record.
	 *
	 * @param id record ID
	 */
	public void setId(long id) {
		this.id = id;
	}

	/**
	 * Returns the name of the user who created the record.
	 *
	 * @return created by user name
	 */
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * Sets the name of the user who created the record.
	 *
	 * @param createdBy created by user name
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * Returns the name of the user who modified the record.
	 *
	 * @return modified by user name
	 */
	public String getModifiedBy() {
		return modifiedBy;
	}

	/**
	 * Sets the name of the user who modified the record.
	 *
	 * @param modifiedBy modified by user name
	 */
	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	/**
	 * Returns the date and time when the record was created.
	 *
	 * @return created date and time
	 */
	public Timestamp getCreatedDatetime() {
		return createdDatetime;
	}

	/**
	 * Sets the date and time when the record was created.
	 *
	 * @param createdDatetime created date and time
	 */
	public void setCreatedDatetime(Timestamp createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	/**
	 * Returns the date and time when the record was modified.
	 *
	 * @return modified date and time
	 */
	public Timestamp getModifiedDatetime() {
		return modifiededDatetime;
	}

	/**
	 * Sets the date and time when the record was modified.
	 *
	 * @param modifiededDatetime modified date and time
	 */
	public void setModifiedDatetime(Timestamp modifiededDatetime) {
		this.modifiededDatetime = modifiededDatetime;
	}

	/**
	 * Sets the common bean attributes from the given ResultSet.
	 *
	 * @param rs ResultSet containing database record data
	 */
	public void setResultset(ResultSet rs) {
		try {
			this.setId(rs.getLong("ID"));
			this.setCreatedBy(rs.getString("CREATED_BY"));
			this.setModifiedBy(rs.getString("MODIFIED_BY"));
			this.setCreatedDatetime(rs.getTimestamp("CREATED_DATETIME"));
			this.setModifiedDatetime(rs.getTimestamp("MODIFIED_DATETIME"));
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	/**
	 * Returns the ID of the bean as a String key.
	 *
	 * @return ID as String
	 */
	@Override
	public String getKey() {
		return id + "";
	}

}
